### ISSUE TITLE
Cannot save the Settings

### ISSUE THREAD

**Issue by heyudude** [BernhardSchlegel/BierBot#20]
Hi,
I installed Bierbot and the server is up and running. I wanted to change the settings but they cannot be saved. The blue Save button is not enabled. Can you help? What can I do to fix this?

**Comment by BernhardSchlegel** [comment]
Hi,

Sorry für the inconveniences! This bug was merged with the telegram support. To get around it, temporarily enable telegram support and fill out the telegram settings (any text). Saving should be possible then.

If you want to submit a PR, that would be very much appreciated. Our focus is currently on BierBot bricks.

Best,
Bernhard.

**Comment by BernhardSchlegel** [comment]
Unintentionally closed

**Comment by heyudude** [comment]
If it is merged and my repo is up to date it should be resolved then? But it is not. What should I do?

Thanks by the way for this beautiful tool!

**Comment by BernhardSchlegel** [comment]
It's not resolved yet. There is only the workaround of activating telegram and filling out the chatID etc. with some value. Bug was **introduced** with the merge of the telegram feature.

**Comment by heyudude** [comment]
thanks, it works now with the workaround.

**Comment by jonathanschneider** [comment]
#21
